author:
  avatar           : "profile.png"
  name             : "Eunju Jeong"
  pronouns         : "she/her"
  bio              : |
    Professor, Department of Music Therapy, Ewha Womans University  
    Director, Ewha Music Intelligence Neuroscience Design Lab  

    Education: Ph.D. Music Education (Music Therapy), University of Miami (2011)  

    Research areas: Music perception & cognition, music-based neurorehabilitation,  
    digital health (VR/AR), sensory branding  

    Achievements (as of 2025):  
    - 40+ peer-reviewed journal articles  
    - 2 registered patents (music therapy device, BCI neurorehab)  
    - 50+ international conference presentations (ISMIR, ICMPC, WFMT, etc.)

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  patents:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
